# Generated by Django 5.0.4 on 2024-04-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_post_gasolina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posto',
            name='litros',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
