# Generated by Django 5.0.4 on 2024-04-28 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_post_gasolina', '0002_posto_litros'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posto',
            new_name='Tabela',
        ),
    ]
